// Auto-generated by scripts/generate-playlist.mjs — do not edit
export const MUSIC_PLAYLIST: readonly string[] = [
  "./music/AnimeLive%20-%20Best%20Friend%20(8%20Bits)%20-%20Lofi%20Hip%20Hop%20(8%20Bits%20Music)%20%F0%9F%8E%A7%F0%9F%8E%B6%20%5BHD%5D%201080p.mp3",
  "./music/pixel%20art%20-%2017%20-%20LoFi%20Boy%208bit%F0%9F%8F%9Dpixel%F0%9F%8F%9D%20lofi%E2%A7%B8chill%20hip%20hop.mp3",
  "./music/pixel%20art%20-%20A%20L%20E%20X%20-%20Ghosts%20-%208bit%F0%9F%8C%89pixel%F0%9F%8C%89%20lofi%20beat%E2%A7%B8chillhop.mp3",
  "./music/pixel%20art%20-%20A%20L%20E%20X%20-%20zeldas%20lullaby%208bit%F0%9F%8C%89pixel%F0%9F%8C%89%20lofi%20beat%E2%A7%B8chillhop.mp3",
  "./music/pixel%20art%20-%20Austin%20Chen%20-%20Faces%208bit%F0%9F%8F%99pixel%F0%9F%8F%99lofi%20beat%E2%A7%B8chillhop.mp3",
  "./music/pixel%20art%20-%20first%20kiss%20-%20elijah%20who%208bit%E2%9B%BCpixel%E2%9B%BC%20a%20e%20s%20t%20h%20e%20t%20i%20c.mp3",
  "./music/pixel%20art%20-%20halberd%20-%20coffee%20on%20the%20beach.%208bit%20%F0%9F%8F%9Dpixel%F0%9F%8F%9D%20lo%20-%20fi%20hiphop.mp3",
  "./music/pixel%20art%20-%20Midnight%20Bounce%20-%20Lakey%20Inspired%208bit%20%F0%9F%8C%83pixel%F0%9F%8C%83%20lo%20-%20fi.mp3",
  "./music/pixel%20art%20-%20summer's%20day%20-%20jinsang%208bit%20Spirited%20Away%20ost%20of%20jibri%20studio.mp3"
];
